In [339]:
import pandas as pd
import gzip

def parse(path):
  g = gzip.open(path, 'rb')
  for l in g:
    yield eval(l)

def getDF(path):
  i = 0
  df = {}
  for d in parse(path):
    df[i] = d
    i += 1
  return pd.DataFrame.from_dict(df, orient='index')

df = getDF('C:/Users/Sanjeev Ramasamy/Downloads/reviews_Electronics_5.json.gz')


KeyboardInterrupt: 

In [348]:
import pandas as pd
df=pd.read_csv("D:/Python/1429_1.csv")

C:\Users\Sanjeev Ramasamy\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (1,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [349]:
df.head()

id                                               name  \
0  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
1  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
2  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
3  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   
4  AVqkIhwDv8e3D1O-lebb  All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...   

        asins   brand                                         categories  \
0  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
1  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
2  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
3  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   
4  B01AHB9CN2  Amazon  Electronics,iPad & Tablets,All Tablets,Fire Ta...   

                                                keys manufacturer  \
0  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
1  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
2  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
3  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   
4  841667104676,amazon/53004484,amazon/b01ahb9cn2...       Amazon   

               reviews.date     reviews.dateAdded  \
0  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
1  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
2  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
3  2017-01-13T00:00:00.000Z  2017-07-03T23:33:15Z   
4  2017-01-12T00:00:00.000Z  2017-07-03T23:33:15Z   

                                    reviews.dateSeen        ...         \
0  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z        ...          
1  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z        ...          
2  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z        ...          
3  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z        ...          
4  2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z        ...          

  reviews.doRecommend reviews.id  reviews.numHelpful  reviews.rating  \
0                True        NaN                 0.0             5.0   
1                True        NaN                 0.0             5.0   
2                True        NaN                 0.0             5.0   
3                True        NaN                 0.0             4.0   
4                True        NaN                 0.0             5.0   

                                  reviews.sourceURLs  \
0  http://reviews.bestbuy.com/3545/5620406/review...   
1  http://reviews.bestbuy.com/3545/5620406/review...   
2  http://reviews.bestbuy.com/3545/5620406/review...   
3  http://reviews.bestbuy.com/3545/5620406/review...   
4  http://reviews.bestbuy.com/3545/5620406/review...   

                                        reviews.text  \
0  This product so far has not disappointed. My c...   
1  great for beginner or experienced person. Boug...   
2  Inexpensive tablet for him to use and learn on...   
3  I've had my Fire HD 8 two weeks now and I love...   
4  I bought this for my grand daughter when she c...   

                             reviews.title reviews.userCity  \
0                                   Kindle              NaN   
1                                very fast              NaN   
2  Beginner tablet for our 9 year old son.              NaN   
3                                  Good!!!              NaN   
4                Fantastic Tablet for kids              NaN   

   reviews.userProvince  reviews.username  
0                   NaN           Adapter  
1                   NaN            truman  
2                   NaN             DaveZ  
3                   NaN            Shacks  
4                   NaN         explore42  

[5 rows x 21 columns]

In [350]:
text=df[['reviews.text','reviews.rating']].copy()

In [351]:
text.columns = ["reviews", "rating"]
text.head()

reviews  rating
0  This product so far has not disappointed. My c...     5.0
1  great for beginner or experienced person. Boug...     5.0
2  Inexpensive tablet for him to use and learn on...     5.0
3  I've had my Fire HD 8 two weeks now and I love...     4.0
4  I bought this for my grand daughter when she c...     5.0

In [352]:
text['Sentiment'] = 1
text.loc[(text['rating'] > 0) & (text['rating'] <= 2), 'Sentiment'] =0
text.loc[(text['rating'] > 3) & (text['rating'] <= 5), 'Sentiment'] = 2
text=text[['reviews','Sentiment']].copy()

In [353]:
text.columns = ["reviews","Sentiment"]

In [ ]:
text.head()

In [354]:
y=text['Sentiment'].values
#X=text['reviews.text'].values
X = text.reviews.fillna(' ')

In [357]:
import sklearn
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)

In [358]:
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
#print(X_train[0])
#print(y_train[0])
#print(X_test[0])
#print(y_test[0])

(20796,) (20796,) (13864,) (13864,)


In [359]:
training_labels = set(y_train)
print(training_labels)
from scipy.stats import itemfreq
training_category_dist = itemfreq(y_train)
print(training_category_dist)

{0, 1, 2}
[[    0   502]
 [    1   954]
 [    2 19340]]


C:\Users\Sanjeev Ramasamy\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  after removing the cwd from sys.path.


In [360]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [361]:
#  unigram boolean vectorizer, set minimum document frequency to 5
unigram_bool_vectorizer = CountVectorizer(encoding='latin-1', binary=True, min_df=5, stop_words='english')

#  unigram term frequency vectorizer, set minimum document frequency to 5
unigram_count_vectorizer = CountVectorizer(encoding='latin-1', binary=False, min_df=5, stop_words='english')

#  unigram and bigram term frequency vectorizer, set minimum document frequency to 5
gram12_count_vectorizer = CountVectorizer(encoding='latin-1', ngram_range=(1,2), min_df=5, stop_words='english')

#  unigram tfidf vectorizer, set minimum document frequency to 5
unigram_tfidf_vectorizer = TfidfVectorizer(encoding='latin-1', use_idf=True, min_df=5, stop_words='english')

In [362]:
X_train_vec1 = unigram_bool_vectorizer.fit_transform(X_train)
X_train_vec2 = unigram_count_vectorizer.fit_transform(X_train)
X_train_vec3 = unigram_tfidf_vectorizer.fit_transform(X_train)
X_train_vec4 = gram12_count_vectorizer.fit_transform(X_train)

In [363]:
#Vectorize the test dataset
X_test_vec1 = unigram_bool_vectorizer.transform(X_test)
X_test_vec2 = unigram_count_vectorizer.transform(X_test)
X_test_vec3 = unigram_tfidf_vectorizer.transform(X_test)

In [364]:
X_test_vec4 = gram12_count_vectorizer.transform(X_test)

In [365]:
# import the MNB module
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

svm_clf = LinearSVC(C=1)
# initialize the MNB model
nb_clf= MultinomialNB()

# use the training data to train the MNB model
#svm_clf.fit(X_train_vec,y_train)
#nb_clf.fit(X_train_vec,y_train)

In [366]:
svm_model1 = svm_clf.fit(X_train_vec1,y_train)
svm_bool = svm_model1.score(X_test_vec1,y_test)
print("SVM_BOOL Score:",svm_bool)

SVM_BOOL Score: 0.9262839007501442


In [367]:
svm_feature_ranks = sorted(zip(svm_model1.coef_[0], unigram_bool_vectorizer.get_feature_names()))
## get the 10 features that are best indicators of very negative sentiment (they are at the bottom of the ranked list)
very_negative_10 = svm_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = svm_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(1.1700572596625316, 'refused')
(1.175495162170946, 'leather')
(1.1755297258835078, 'overdrive')
(1.1880102199258604, 'damaged')
(1.2141045747857873, 'terrible')
(1.2771417922977548, 'waste')
(1.3653509814523388, 'dust')
(1.3892617466152772, 'accessibility')
(1.4323304894568045, 'advice')
(1.5066043807121505, 'comfortably')

not very negative words
(-1.54727473232284, 'allowed')
(-1.3575625509221558, 'desk')
(-1.1800077403759661, 'break')
(-1.1090125438950047, 'lady')
(-1.1077445589045367, 'instagram')
(-1.106019640740882, 'laptop')
(-1.0863756286581552, 'browser')
(-1.0693418758773088, 'hd')
(-1.0434765824916354, 'frozen')
(-1.0214474014033168, 'stick')



In [368]:
# print confusion matrix and classification report

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
y_pred = svm_model1.predict(X_test_vec1)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()

target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[   75    55   180]
 [   43    89   446]
 [   76   222 12678]]

              precision    recall  f1-score   support

           0       0.39      0.24      0.30       310
           1       0.24      0.15      0.19       578
           2       0.95      0.98      0.96     12976

   micro avg       0.93      0.93      0.93     13864
   macro avg       0.53      0.46      0.48     13864
weighted avg       0.91      0.93      0.92     13864



In [411]:
svm_model2 = svm_clf.fit(X_train_vec2,y_train)
svm_count = svm_model2.score(X_train_vec2,y_train)
print("SCM_COUNT_VECT Score:",svm_count)

SCM_COUNT_VECT Score: 0.9737930371225235


C:\Users\Sanjeev Ramasamy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [412]:
svm_feature_ranks = sorted(zip(svm_model2.coef_[0], unigram_count_vectorizer.get_feature_names()))
very_negative_10 = svm_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = svm_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(1.1378535600726738, 'bloatware')
(1.1438991800393812, 'leather')
(1.1514338066669312, 'barely')
(1.1718219565978045, 'waste')
(1.2333940364016094, 'terrible')
(1.3352455457602035, 'damaged')
(1.4022013003722333, 'comfortably')
(1.4467378584040955, 'dust')
(1.4703316073138037, 'advice')
(1.5017629006311344, 'accessibility')

not very negative words
(-1.6055630125914653, 'allowed')
(-1.1610864280028337, 'excellent')
(-1.1403708203342486, 'desk')
(-1.0941849606197678, 'overall')
(-1.0716095686681923, 'browser')
(-1.0682998587956094, 'dropping')
(-1.0479614870696425, 'frozen')
(-1.044033108234935, 'assistance')
(-1.0414857544717213, 'laptop')
(-1.0410931409869446, 'break')



In [413]:
y_pred = svm_model2.predict(X_test_vec2)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()


target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[   77    55   178]
 [   46    89   443]
 [   91   223 12662]]

              precision    recall  f1-score   support

           0       0.36      0.25      0.29       310
           1       0.24      0.15      0.19       578
           2       0.95      0.98      0.96     12976

   micro avg       0.93      0.93      0.93     13864
   macro avg       0.52      0.46      0.48     13864
weighted avg       0.91      0.93      0.92     13864



In [372]:
svm_model3 = svm_clf.fit(X_train_vec3,y_train)
svm_tfidf = svm_model3.score(X_test_vec3,y_test)
print("SVM_TFIDF_Score:", svm_tfidf)

SVM_TFIDF_Score: 0.9367426428159261


In [373]:
svm_feature_ranks = sorted(zip(svm_model3.coef_[0], unigram_tfidf_vectorizer.get_feature_names()))
very_negative_10 = svm_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = svm_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(1.5829769878140716, 'refurbished')
(1.5985953070142824, 'poor')
(1.6046804237275036, 'disappointed')
(1.617294077880973, 'hopes')
(1.625479761163857, 'returned')
(1.671776065749695, 'returning')
(1.7842633804616337, 'waste')
(1.7844531319174677, 'barely')
(1.7947553651934098, 'useless')
(2.0308106455033434, 'terrible')

not very negative words
(-1.6723727912898299, 'great')
(-1.579797499129392, 'stick')
(-1.4416254668080462, 'overall')
(-1.3982451750726355, 'easy')
(-1.3097029962977214, 'excellent')
(-1.2958161166021203, 'hd')
(-1.2477508905874737, 'love')
(-1.2150916885180088, 'reading')
(-1.125124532893256, 'laptop')
(-1.003718077415268, 'pleased')



In [374]:
y_pred = svm_model3.predict(X_test_vec3)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()


target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[   58    36   216]
 [   28    37   513]
 [   29    55 12892]]

              precision    recall  f1-score   support

           0       0.50      0.19      0.27       310
           1       0.29      0.06      0.10       578
           2       0.95      0.99      0.97     12976

   micro avg       0.94      0.94      0.94     13864
   macro avg       0.58      0.41      0.45     13864
weighted avg       0.91      0.94      0.92     13864



In [375]:
svm_model4 = svm_clf.fit(X_train_vec4,y_train)
svm_ngram = svm_model4.score(X_test_vec4, y_test)
print("SVM_NGRAM Score:",svm_ngram)

SVM_NGRAM Score: 0.9199365262550491


In [376]:
svm_feature_ranks = sorted(zip(svm_model4.coef_[0], gram12_count_vectorizer.get_feature_names()))
very_negative_10 = svm_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = svm_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(1.012894273121367, 'bloatware')
(1.0151058445274097, 'want buy')
(1.0221574273134681, 'damaged')
(1.023874148364283, 'advice')
(1.035198111264926, 'comfortably')
(1.0686129980268941, 'price awesome')
(1.0838661158830638, 'night light')
(1.0905801865357994, 'great year')
(1.21552454040574, 'kindle perfect')
(1.4207349440993882, 'need help')

not very negative words
(-0.9021454156852892, 'frozen')
(-0.8547670083067317, 'laptop')
(-0.8449513343801914, 'overall')
(-0.8436830221303548, 'stick')
(-0.8411691554254214, 'holding')
(-0.8141050047739389, 'excellent')
(-0.7973407697590842, 'amazon echo')
(-0.7795168222260991, 'easy')
(-0.7668394727424561, 'great product')
(-0.7584938187197625, 'didn need')



In [377]:
y_pred = svm_model4.predict(X_test_vec4)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()
target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[   83    61   166]
 [   49    91   438]
 [   91   305 12580]]

              precision    recall  f1-score   support

           0       0.37      0.27      0.31       310
           1       0.20      0.16      0.18       578
           2       0.95      0.97      0.96     12976

   micro avg       0.92      0.92      0.92     13864
   macro avg       0.51      0.46      0.48     13864
weighted avg       0.91      0.92      0.91     13864



In [378]:
nb_model1 = nb_clf.fit(X_train_vec1,y_train)
nb_bool = nb_model1.score(X_test_vec1,y_test)
print("NB_Boolean Score:",nb_bool)

NB_Boolean Score: 0.9218118869013272


In [379]:
nb_feature_ranks = sorted(zip(nb_model1.coef_[0], unigram_bool_vectorizer.get_feature_names()))
very_negative_10 = nb_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = nb_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(-5.233864863216204, 'product')
(-5.17134450623487, 'good')
(-5.17134450623487, 'like')
(-5.141491543085189, 'kindle')
(-5.112504006211936, 'buy')
(-5.09831937121998, 'use')
(-5.056934155057125, 'just')
(-4.954280000997042, 'bought')
(-4.633611429548955, 'tablet')
(-4.448344362525243, 'amazon')

not very negative words
(-9.360999248261296, '10x')
(-9.360999248261296, '128')
(-9.360999248261296, '128gb')
(-9.360999248261296, '150')
(-9.360999248261296, '16g')
(-9.360999248261296, '16gb')
(-9.360999248261296, '17')
(-9.360999248261296, '18')
(-9.360999248261296, '2011')
(-9.360999248261296, '2012')



In [380]:
y_pred = nb_model1.predict(X_test_vec1)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()
target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[   87    73   150]
 [   40   118   420]
 [  107   294 12575]]

              precision    recall  f1-score   support

           0       0.37      0.28      0.32       310
           1       0.24      0.20      0.22       578
           2       0.96      0.97      0.96     12976

   micro avg       0.92      0.92      0.92     13864
   macro avg       0.52      0.48      0.50     13864
weighted avg       0.91      0.92      0.92     13864



In [381]:
nb_model2 = nb_clf.fit(X_train_vec2,y_train)
nb_count = nb_model2.score(X_test_vec2,y_test)
print("NB_Count Score:",nb_count)

NB_Count Score: 0.9214512406231967


In [382]:
nb_feature_ranks = sorted(zip(nb_model2.coef_[0], unigram_count_vectorizer.get_feature_names()))
very_negative_10 = nb_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = nb_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(-5.081640204771728, 'device')
(-5.069061422564868, 'apps')
(-5.020271258395436, 'like')
(-4.9851799385841655, 'use')
(-4.973751242760542, 'buy')
(-4.96245168750661, 'just')
(-4.9402285507218995, 'bought')
(-4.816359069009113, 'kindle')
(-4.357337856431987, 'tablet')
(-4.209341042179107, 'amazon')

not very negative words
(-9.45108805723875, '10x')
(-9.45108805723875, '128')
(-9.45108805723875, '128gb')
(-9.45108805723875, '150')
(-9.45108805723875, '16g')
(-9.45108805723875, '16gb')
(-9.45108805723875, '17')
(-9.45108805723875, '18')
(-9.45108805723875, '2011')
(-9.45108805723875, '2012')



In [383]:
y_pred = nb_model2.predict(X_test_vec2)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()
target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[   99    74   137]
 [   48   123   407]
 [  101   322 12553]]

              precision    recall  f1-score   support

           0       0.40      0.32      0.35       310
           1       0.24      0.21      0.22       578
           2       0.96      0.97      0.96     12976

   micro avg       0.92      0.92      0.92     13864
   macro avg       0.53      0.50      0.51     13864
weighted avg       0.92      0.92      0.92     13864



In [384]:
nb_model3 = nb_clf.fit(X_train_vec3,y_train)
nb_tfdf = nb_model3.score(X_test_vec3,y_test)
print("NB_TFIDF SCore:",nb_tfdf)

NB_TFIDF SCore: 0.9363819965377957


In [385]:
nb_feature_ranks = sorted(zip(nb_model3.coef_[0], unigram_tfidf_vectorizer.get_feature_names()))
very_negative_10 = nb_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = nb_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(-6.080778852486594, 'bought')
(-6.055817559456606, 'just')
(-6.034696873043576, 'apps')
(-6.033012129094146, 'kindle')
(-5.960356734657003, 'don')
(-5.959442485797114, 'buy')
(-5.95292311397702, 'slow')
(-5.933110089174585, 'returned')
(-5.691932322822391, 'tablet')
(-5.547766948861756, 'amazon')

not very negative words
(-8.547880916516542, '10x')
(-8.547880916516542, '128')
(-8.547880916516542, '128gb')
(-8.547880916516542, '150')
(-8.547880916516542, '16g')
(-8.547880916516542, '16gb')
(-8.547880916516542, '17')
(-8.547880916516542, '18')
(-8.547880916516542, '2011')
(-8.547880916516542, '2012')



In [386]:
y_pred = nb_model3.predict(X_test_vec3)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()
target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[    4     2   304]
 [    1     3   574]
 [    0     1 12975]]

              precision    recall  f1-score   support

           0       0.80      0.01      0.03       310
           1       0.50      0.01      0.01       578
           2       0.94      1.00      0.97     12976

   micro avg       0.94      0.94      0.94     13864
   macro avg       0.75      0.34      0.33     13864
weighted avg       0.92      0.94      0.91     13864



In [387]:
nb_model4 = nb_clf.fit(X_train_vec4,y_train)
nb_ngram = nb_model4.score(X_test_vec4,y_test)
print("NB_NGRAM Score:",nb_ngram)

NB_NGRAM Score: 0.9241921523369879


In [388]:
nb_feature_ranks = sorted(zip(nb_model4.coef_[0], gram12_count_vectorizer.get_feature_names()))
very_negative_10 = nb_feature_ranks[-10:]
print("Very negative words")
for i in range(0, len(very_negative_10)):
    print(very_negative_10[i])
print()

## get 10 features that are least relevant to "very negative" sentiment (they are at the top of the ranked list)
not_very_negative_10 = nb_feature_ranks[:10]
print("not very negative words")
for i in range(0, len(not_very_negative_10)):
    print(not_very_negative_10[i])
print()

Very negative words
(-5.618518706647046, 'device')
(-5.605939924440186, 'apps')
(-5.557149760270754, 'like')
(-5.5220584404594835, 'use')
(-5.51062974463586, 'buy')
(-5.4993301893819275, 'just')
(-5.477107052597217, 'bought')
(-5.353237570884431, 'kindle')
(-4.894216358307305, 'tablet')
(-4.746219544054425, 'amazon')

not very negative words
(-9.987966559114067, '10 inch')
(-9.987966559114067, '10 love')
(-9.987966559114067, '10 minutes')
(-9.987966559114067, '10 year')
(-9.987966559114067, '10 years')
(-9.987966559114067, '10 yr')
(-9.987966559114067, '100 dollars')
(-9.987966559114067, '100 month')
(-9.987966559114067, '10x')
(-9.987966559114067, '11 year')



In [389]:
y_pred = nb_model4.predict(X_test_vec4)
cm=confusion_matrix(y_test, y_pred, labels=[0,1,2])
print(cm)
print()
target_names = ['0','1','2']
print(classification_report(y_test, y_pred, target_names=target_names))

[[   72    91   147]
 [   25   150   403]
 [   63   322 12591]]

              precision    recall  f1-score   support

           0       0.45      0.23      0.31       310
           1       0.27      0.26      0.26       578
           2       0.96      0.97      0.96     12976

   micro avg       0.92      0.92      0.92     13864
   macro avg       0.56      0.49      0.51     13864
weighted avg       0.92      0.92      0.92     13864



In [414]:
svm_model2 = svm_clf.fit(X_train_vec2,y_train)
svm_count = svm_model2.score(X_train_vec2,y_train)
print("SCM_COUNT_VECT Score:",svm_count)
y_pred = svm_model2.predict(X_test_vec2)

SCM_COUNT_VECT Score: 0.9737930371225235


C:\Users\Sanjeev Ramasamy\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [415]:
output=pd.DataFrame()
output["reviews"]=list(X_test)
output["Prediction"]=y_pred


In [416]:
output[1:20]

reviews  Prediction
1   It's very durable and Nice picture.its the per...           2
2   Fire TV helps me navigate several viewing sour...           2
3   Touch is not good. Also very limited apps on a...           2
4   This is one cool item. It doesn't take up a lo...           2
5   It's amazing and I will like to tell a friend ...           2
6   Amazon has hit it out of the park with this on...           2
7   Perfect device for kids learning how to use to...           2
8   I bought this thinking it was needed for the E...           2
9   Makes lists for me, plays music, tells me the ...           2
10  Pretty good sound for the size and configurati...           2
11  perfect size; good graphics; app store is exte...           2
12  Great product. I have two of these and a coupl...           2
13  Absolutely makes my home feel more updated. I ...           2
14  Absolutely can't get enough of my fire TV. Bes...           2
15  I bought this for my sister as a birthday gift...           2
16  I am just learning all the possible functions ...           2
17  not as smart as the commercials show. cant ans...           2
18  Great video quality lots of fun apps fun for t...           2
19  The tablet could be great for my 4 year old da...           0

In [417]:
Testing2=output.loc[output['Prediction'] == 2]
Testing1=output.loc[output['Prediction'] == 1]
Testing0=output.loc[output['Prediction'] == 0]

In [418]:
print(len(Testing2))
print(len(Testing1))
print(len(Testing0))

13283
367
214


In [419]:
Testing2.head()

reviews  Prediction
0  Amazon - Kindle Paperwhite is moe like reading...           2
1  It's very durable and Nice picture.its the per...           2
2  Fire TV helps me navigate several viewing sour...           2
3  Touch is not good. Also very limited apps on a...           2
4  This is one cool item. It doesn't take up a lo...           2

In [420]:
no_features = 1000
tf_vectorizer = CountVectorizer(max_df=0.95, min_df=2, max_features=no_features, stop_words='english')

In [421]:
tf = tf_vectorizer.fit_transform(list(Testing2["reviews"]))
tf_feature_names = tf_vectorizer.get_feature_names()

In [422]:
from sklearn.decomposition import NMF, LatentDirichletAllocation

no_topics = 20
lda = LatentDirichletAllocation(n_components=no_topics, max_iter=5, learning_method='online', learning_offset=50.,random_state=0)
lda_z = lda.fit_transform(tf)

In [423]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic %d:" % (topic_idx))
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-no_top_words - 1:-1]]))

no_top_words = 10

In [424]:
display_topics(lda, tf_feature_names, no_top_words)

Topic 0:
time play questions child plays music tell ask favorite keeps
Topic 1:
best buy device far money amazon price ipad search apple
Topic 2:
amazon prime app store enjoy apps free google available android
Topic 3:
worth definitely big upgrade expected better hard hands option exactly
Topic 4:
purchased recommend son highly friends husband bought recommended gift likes
Topic 5:
kindle battery new life long especially time charge love great
Topic 6:
better fast screen picture clear camera memory size faster purse
Topic 7:
games kids tablet great use easy apps play love user
Topic 8:
echo alexa music home love use great amazon speaker voice
Topic 9:
needed buying went started school taking purpose loaded ebooks hooked
Topic 10:
just don like getting little did used right thing know
Topic 11:
tv amazon watch movies box stick great streaming use love
Topic 12:
love wife bought item years absolutely things purchased christmas friend
Topic 13:
cable ve wish time decided pay high month ex

In [425]:
tf = tf_vectorizer.fit_transform(list(Testing1["reviews"]))
tf_feature_names = tf_vectorizer.get_feature_names()

In [426]:
from sklearn.decomposition import NMF, LatentDirichletAllocation

no_topics = 20
lda = LatentDirichletAllocation(n_components=no_topics, max_iter=5, learning_method='online', learning_offset=50.,random_state=0)
lda_z = lda.fit_transform(tf)

In [427]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic %d:" % (topic_idx))
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-no_top_words - 1:-1]]))

no_top_words = 10

In [428]:
display_topics(lda, tf_feature_names, no_top_words)

Topic 0:
good tablet basic use complaint far don close owned explain
Topic 1:
tablet good amazon price just bought use great like apps
Topic 2:
4k like apple tv small speed older purchased work version
Topic 3:
tablet hard books bought perfectly version reading quality amazon size
Topic 4:
say make port send able attempted charging thought calls care
Topic 5:
yr worthy wireless day experience dont games mini went major
Topic 6:
doesn work works phone screen does good pretty properly amazon
Topic 7:
tablet things amazon pay slow charger price sure kindle did
Topic 8:
ok tv members controlled apparently speaker thought stock learn pc
Topic 9:
kids purchases product account tablets great accounts did amazon using
Topic 10:
larger dot tablet speaker nice speakers external use games leave
Topic 11:
screen lot order slow great does tablet needs detergent alexa
Topic 12:
work sad open tab greatest fi minimal android standby wi
Topic 13:
satisfy bit program know option coming amazons fee child

In [429]:
tf = tf_vectorizer.fit_transform(list(Testing0["reviews"]))
tf_feature_names = tf_vectorizer.get_feature_names()

In [430]:
from sklearn.decomposition import NMF, LatentDirichletAllocation
no_topics = 20
lda = LatentDirichletAllocation(n_components=no_topics, max_iter=5, learning_method='online', learning_offset=50.,random_state=0)
lda_z = lda.fit_transform(tf)

In [431]:
def display_topics(model, feature_names, no_top_words):
    for topic_idx, topic in enumerate(model.components_):
        print("Topic %d:" % (topic_idx))
        print(" ".join([feature_names[i]
                        for i in topic.argsort()[:-no_top_words - 1:-1]]))

no_top_words = 10

In [432]:
display_topics(lda, tf_feature_names, no_top_words)

Topic 0:
processor 4k money stock got speed told faster went second
Topic 1:
amazon books device read membership account free calls wasn setup
Topic 2:
alexa questions review love work maybe just grandchildren guess young
Topic 3:
kindle amazon charge just like read page bought don oasis
Topic 4:
disappointed use doesn mode screen display apps price work daughter
Topic 5:
news home kind going review basic did webroot place ask
Topic 6:
kindle time wifi just amazon problem tried got connect product
Topic 7:
google like won amazon android think buy got youtube best
Topic 8:
instructions came does returned worth different searching gave using frustrating
Topic 9:
says alexa connection later getting want sucks check minutes works
Topic 10:
touch page pdf kindle doesn paper book liked font turning
Topic 11:
kept customer working service friendly type couldn recommend took person
Topic 12:
charge definitely won recommend kindles replacement charging problem does 10
Topic 13:
internet didn pi